# Generated by Django 5.2.5 on 2026-06-22 12:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('procesadas', models.PositiveIntegerField(default=0)),
                ('exitosas', models.PositiveIntegerField(default=0)),
                ('fallidas', models.PositiveIntegerField(default=0)),
                ('duplicadas', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('en_cola', 'En cola'), ('procesando', 'Procesando'), ('completado', 'Completado'), ('con_errores', 'Completado con errores')], default='en_cola', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('terminado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='accounts.negocio')),
            ],
            options={
                'verbose_name': 'Lote de carga',
                'verbose_name_plural': 'Lotes de carga',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('leida', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('de', models.CharField(default='No encontrada', max_length=200, verbose_name='Remitente')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_raw', models.CharField(blank=True, default='', max_length=50)),
                ('fecha', models.CharField(blank=True, default='', max_length=60)),
                ('hora', models.CharField(blank=True, default='', max_length=30)),
                ('ref', models.CharField(blank=True, default='', max_length=80, verbose_name='Referencia')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='comprobantes/%Y/%m/')),
                ('fuente_ia', models.CharField(blank=True, default='', max_length=20)),
                ('origen', models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram')], default='web', max_length=20)),
                ('confirmado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprobantes', to='accounts.negocio')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes', to='comprobantes.lotecarga')),
            ],
            options={
                'verbose_name': 'Comprobante',
                'verbose_name_plural': 'Comprobantes',
                'ordering': ['-creado_en'],
                'indexes': [models.Index(fields=['negocio', 'ref'], name='comprobante_negocio_792534_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(models.Q(('ref', ''), _negated=True), models.Q(('ref', 'No encontrada'), _negated=True)), fields=('negocio', 'ref'), name='ref_unica_por_negocio')],
            },
        ),
    ]
