# Generated by Django 6.0.6 on 2026-06-22 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comprobante',
            name='confirmado',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='estado',
            field=models.CharField(choices=[('sin_confirmar', 'Sin confirmar'), ('confirmado', 'Confirmado')], default='sin_confirmar', max_length=20),
        ),
    ]
