# Generated by Django 6.0.6 on 2026-06-22 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('comprobantes', '0002_remove_comprobante_confirmado_comprobante_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='fecha_dt',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('nombre', models.CharField(blank=True, default='', max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='accounts.negocio')),
            ],
            options={
                'verbose_name': 'Ruta',
                'verbose_name_plural': 'Rutas',
                'ordering': ['numero'],
            },
        ),
        migrations.AddField(
            model_name='comprobante',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes', to='comprobantes.ruta'),
        ),
        migrations.AddConstraint(
            model_name='ruta',
            constraint=models.UniqueConstraint(fields=('negocio', 'numero'), name='ruta_unica_por_negocio'),
        ),
    ]
