# Generated by Django 6.0.6 on 2026-06-22 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0003_comprobante_fecha_dt_ruta_comprobante_ruta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivoPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='pendientes/%Y/%m/')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='comprobantes.lotecarga')),
            ],
            options={
                'verbose_name': 'Archivo pendiente',
                'verbose_name_plural': 'Archivos pendientes',
                'ordering': ['id'],
            },
        ),
    ]
