# Generated by Django 6.0.6 on 2026-06-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0004_archivopendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivopendiente',
            name='fallido',
            field=models.BooleanField(default=False),
        ),
    ]
