# Generated by Django 5.2.5 on 2026-06-27 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfilusuario_es_especial'),
        ('comprobantes', '0005_archivopendiente_fallido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='comprobante',
            name='ref_unica_por_negocio',
        ),
        migrations.AddField(
            model_name='comprobante',
            name='duplicado_de',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicados', to='comprobantes.comprobante'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='es_duplicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='comprobante',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('ref', ''), _negated=True), models.Q(('ref', 'No encontrada'), _negated=True), ('es_duplicado', False)), fields=('negocio', 'ref'), name='ref_unica_por_negocio'),
        ),
    ]
