# Generated by Django 5.2.5 on 2026-06-27 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0006_remove_comprobante_ref_unica_por_negocio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='archivopendiente',
            name='error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='lotecarga',
            name='estado',
            field=models.CharField(choices=[('en_cola', 'En cola'), ('procesando', 'Procesando'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('con_errores', 'Completado con errores')], default='en_cola', max_length=20),
        ),
    ]
