# Generated by Django 5.2.5 on 2026-06-28 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0007_archivopendiente_error_alter_lotecarga_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='origen',
            field=models.CharField(choices=[('web', 'Web'), ('telegram', 'Telegram'), ('manual', 'Manual')], default='web', max_length=20),
        ),
    ]
