# Generated by Django 5.2.5 on 2026-08-16 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0008_alter_comprobante_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotecarga',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('en_cola', 'En cola'), ('procesando', 'Procesando'), ('pausado', 'Pausado'), ('completado', 'Completado'), ('con_errores', 'Completado con errores')], default='en_cola', max_length=20),
        ),
    ]
