# Generated by Django 6.0.6 on 2026-09-15 06:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def rellenar_trazabilidad(apps, schema_editor):
    """Reconstruye lo posible para los ya confirmados: si hay un ítem OK de
    conciliación, se toma como origen (fecha aproximada = creación del ítem).
    Los demás quedan sin vía (confirmados antes de existir el historial)."""
    Comprobante = apps.get_model("comprobantes", "Comprobante")
    Conciliacion = apps.get_model("conciliaciones", "Conciliacion")
    oks = (Conciliacion.objects.filter(resultado="ok", comprobante__estado="confirmado")
           .select_related("lote", "comprobante").order_by("creado_en", "id"))
    vistos = set()
    for item in oks:
        if item.comprobante_id in vistos:
            continue
        vistos.add(item.comprobante_id)
        comp = item.comprobante
        comp.confirmado_via = "conc_agregar" if comp.origen == "manual" else "conciliacion"
        comp.confirmado_en = item.creado_en
        comp.confirmado_por_id = item.lote.creado_por_id
        comp.confirmado_conciliacion_id = item.pk
        comp.save(update_fields=["confirmado_via", "confirmado_en",
                                 "confirmado_por", "confirmado_conciliacion"])


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0010_suscripcionpush'),
        ('conciliaciones', '0006_alter_loteconciliacion_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='confirmado_conciliacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='conciliaciones.conciliacion'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='confirmado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='confirmado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comprobantes_confirmados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='confirmado_via',
            field=models.CharField(blank=True, choices=[('conciliacion', 'Conciliación automática'), ('conc_pendiente', 'Conciliación (pendiente confirmado a mano)'), ('conc_agregar', 'Conciliación (añadido y confirmado a mano)'), ('lista', 'Manual desde el listado'), ('edicion', 'Manual al editar'), ('importacion', 'Importación de Excel')], default='', max_length=20),
        ),
        migrations.RunPython(rellenar_trazabilidad, migrations.RunPython.noop),
    ]
