# Generated by Django 5.2.5 on 2026-06-23 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='es_especial',
            field=models.BooleanField(default=False, verbose_name='Modo romántico (Especial)'),
        ),
    ]
