# Generated by Django 6.0.6 on 2026-06-28 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_perfilusuario_es_especial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='titular_nequi',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Titular Nequi'),
        ),
    ]
