# Generated by Django 5.2.5 on 2026-06-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_prefill_titular_nequi'),
    ]

    operations = [
        migrations.AddField(
            model_name='negocio',
            name='numero_nequi',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Número Nequi'),
        ),
    ]
