# Generated by Django 6.0.6 on 2026-06-22 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('comprobantes', '0003_comprobante_fecha_dt_ruta_comprobante_ruta_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoteConciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.PositiveIntegerField(default=0)),
                ('procesadas', models.PositiveIntegerField(default=0)),
                ('ok', models.PositiveIntegerField(default=0)),
                ('pendientes', models.PositiveIntegerField(default=0)),
                ('no_esta', models.PositiveIntegerField(default=0)),
                ('estado', models.CharField(choices=[('en_cola', 'En cola'), ('procesando', 'Procesando'), ('completado', 'Completado')], default='en_cola', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('terminado_en', models.DateTimeField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_conciliacion', to=settings.AUTH_USER_MODEL)),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_conciliacion', to='accounts.negocio')),
                ('ruta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_conciliacion', to='comprobantes.ruta')),
            ],
            options={
                'verbose_name': 'Lote de conciliación',
                'verbose_name_plural': 'Lotes de conciliación',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Conciliacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='conciliaciones/%Y/%m/')),
                ('de', models.CharField(blank=True, default='', max_length=200)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('valor_raw', models.CharField(blank=True, default='', max_length=50)),
                ('fecha', models.CharField(blank=True, default='', max_length=60)),
                ('fecha_dt', models.DateField(blank=True, db_index=True, null=True)),
                ('hora', models.CharField(blank=True, default='', max_length=30)),
                ('ref', models.CharField(blank=True, default='', max_length=80)),
                ('resultado', models.CharField(blank=True, choices=[('ok', 'OK'), ('pendiente', 'Pendiente'), ('no_esta', 'No está')], max_length=20, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliaciones', to='comprobantes.comprobante')),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conciliaciones', to='accounts.negocio')),
                ('ruta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conciliaciones', to='comprobantes.ruta')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='conciliaciones.loteconciliacion')),
            ],
            options={
                'verbose_name': 'Conciliación',
                'verbose_name_plural': 'Conciliaciones',
                'ordering': ['id'],
            },
        ),
    ]
