# Generated by Django 5.2.5 on 2026-06-28 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciliacion',
            name='aviso',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='conciliacion',
            name='motivo_revision',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='conciliacion',
            name='para',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Destinatario/Titular'),
        ),
        migrations.AddField(
            model_name='conciliacion',
            name='tipo',
            field=models.CharField(blank=True, choices=[('voucher', 'Voucher (corresponsal)'), ('nequi', 'Comprobante Nequi'), ('otro', 'Otro')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='loteconciliacion',
            name='duplicados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='loteconciliacion',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='conciliacion',
            name='resultado',
            field=models.CharField(blank=True, choices=[('ok', 'OK'), ('pendiente', 'Pendiente'), ('no_esta', 'No está'), ('revision', 'Revisión manual'), ('duplicado', 'Duplicado')], max_length=20, null=True),
        ),
    ]
