# Generated by Django 5.2.5 on 2026-06-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliaciones', '0002_conciliacion_aviso_conciliacion_motivo_revision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loteconciliacion',
            name='estado',
            field=models.CharField(choices=[('en_cola', 'En cola'), ('procesando', 'Procesando'), ('pausado', 'Pausado'), ('completado', 'Completado')], default='en_cola', max_length=20),
        ),
    ]
