# Generated by Django 5.2.5 on 2026-06-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliaciones', '0003_alter_loteconciliacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciliacion',
            name='num',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Número destino'),
        ),
    ]
