# Generated by Django 6.0.6 on 2026-07-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliaciones', '0004_conciliacion_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='conciliacion',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
    ]
